generator:
  class: sfDoctrineGenerator
  param:
    model_class:           GessehEval
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gesseh_eval
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Commentaires publiés
        display: [GessehStage, GessehCritere, Valeur]
        fields:
          GessehStage: { label: Stage }
          GessehCritere: { label: Critere }
          valeur: { label: Commentaire }
        table_method: retrieveComments
        max_per_page: 50
        actions: {}
      filter:
        class: false
      form:    ~
      edit:
        title: Modération du commentaire
        fields:
          valeur: { label: Commentaire }
      new: {}
